name: share_buy
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  fluttertoast: ^8.2.4
  dio: ^5.4.1
  curl_logger_dio_interceptor: ^1.0.0
  pretty_dio_logger: ^1.3.1
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  shared_preferences: ^2.2.3
  skeletonizer: ^1.3.0
  flutter_screenutil: ^5.9.3
  money_formatter: ^0.0.5
  firebase_core: ^3.5.0
  google_fonts: ^6.2.1
  text_divider: ^1.0.0
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  auto_height_grid_view: ^1.0.0
  animated_rating_stars: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
